text = str(input('speak your will'))
text_length = len(text)
print('         {}'.format('_'*text_length))
print('       < {} >'.format(text))
print('         {}'.format('-'*text_length))
print('        /')
print(' /\_/\ /')
print('( o.o )')
print(' > ^ <')